/**
 * Built-in UK GDPR Article 35 DPIA questionnaire (v1).
 *
 * Structure follows the ICO DPIA template phases: describe → consult →
 * assess necessity/proportionality → identify risks → identify measures.
 * Branching (`visibleWhen`) provides skip-logic and automatic follow-ups;
 * `riskTags` on options feed the risk engine.
 */
export const UK_DPIA_TEMPLATE = {
  key: 'uk-dpia',
  name: 'UK GDPR DPIA (ICO-aligned)',
  version: 1,
  description: 'Data Protection Impact Assessment aligned to UK GDPR Article 35 and ICO guidance.',
  sections: [
    {
      key: 'context',
      title: 'Processing context',
      description:
        'Describe the nature, scope, context and purposes of the processing (Art. 35(7)(a)).',
      questions: [
        {
          key: 'processing_name',
          type: 'TEXT',
          label: 'What is the processing activity called?',
          placeholder: 'e.g. Patient triage chatbot',
          required: true,
        },
        {
          key: 'processing_purpose',
          type: 'TEXTAREA',
          label: 'Describe the purpose of the processing and the intended outcomes.',
          help: 'Explain why the processing is needed and what it achieves for you and for the data subjects.',
          required: true,
          references: ['UK GDPR Art. 35(7)(a)'],
          aiHint:
            'A strong answer states the business objective, the benefit to data subjects, and why the processing is necessary to achieve it.',
        },
        {
          key: 'industry',
          type: 'SINGLE_SELECT',
          label: 'Which sector best describes this processing?',
          required: true,
          options: [
            { value: 'healthcare', label: 'Healthcare' },
            { value: 'financial', label: 'Financial services' },
            { value: 'government', label: 'Government / public sector' },
            { value: 'education', label: 'Education' },
            { value: 'retail', label: 'Retail / e-commerce' },
            { value: 'technology', label: 'Technology / SaaS' },
            { value: 'charity', label: 'Charity / non-profit' },
            { value: 'other', label: 'Other' },
          ],
        },
        {
          key: 'lawful_basis',
          type: 'SINGLE_SELECT',
          label: 'What is the lawful basis for the processing?',
          required: true,
          references: ['UK GDPR Art. 6(1)'],
          options: [
            { value: 'CONSENT', label: 'Consent (Art. 6(1)(a))' },
            { value: 'CONTRACT', label: 'Contract (Art. 6(1)(b))' },
            { value: 'LEGAL_OBLIGATION', label: 'Legal obligation (Art. 6(1)(c))' },
            { value: 'VITAL_INTERESTS', label: 'Vital interests (Art. 6(1)(d))' },
            { value: 'PUBLIC_TASK', label: 'Public task (Art. 6(1)(e))' },
            { value: 'LEGITIMATE_INTERESTS', label: 'Legitimate interests (Art. 6(1)(f))' },
          ],
        },
        {
          key: 'legitimate_interests_detail',
          type: 'TEXTAREA',
          label: 'Summarise your legitimate interests assessment (purpose, necessity, balancing).',
          required: true,
          visibleWhen: { q: 'lawful_basis', op: 'eq', value: 'LEGITIMATE_INTERESTS' },
          references: ['ICO legitimate interests guidance'],
          aiHint: 'Cover the three-part test: purpose, necessity, and the balancing of interests.',
        },
        {
          key: 'consent_mechanism',
          type: 'TEXTAREA',
          label: 'How is consent collected, recorded and withdrawn?',
          required: true,
          visibleWhen: { q: 'lawful_basis', op: 'eq', value: 'CONSENT' },
          references: ['UK GDPR Art. 7'],
        },
        {
          key: 'dpo_consulted',
          type: 'BOOLEAN',
          label: 'Has your Data Protection Officer been consulted?',
          required: true,
          references: ['UK GDPR Art. 35(2)'],
        },
      ],
    },
    {
      key: 'data',
      title: 'Data and data subjects',
      questions: [
        {
          key: 'data_categories',
          type: 'MULTI_SELECT',
          label: 'Which categories of personal data are processed?',
          required: true,
          options: [
            { value: 'BASIC_PERSONAL', label: 'Basic personal details (name, DOB)' },
            { value: 'CONTACT', label: 'Contact details' },
            { value: 'IDENTIFIERS', label: 'Online / device identifiers' },
            { value: 'FINANCIAL', label: 'Financial data', riskTags: ['tag:financial'] },
            { value: 'LOCATION', label: 'Location data', riskTags: ['tag:location'] },
            {
              value: 'BEHAVIOURAL',
              label: 'Behavioural / profiling data',
              riskTags: ['tag:tracking'],
            },
            { value: 'EMPLOYMENT', label: 'Employment data' },
            { value: 'IMAGES_AV', label: 'Images / audio / video' },
            {
              value: 'HEALTH',
              label: 'Health data (special category)',
              riskTags: ['tag:special-category', 'tag:health'],
            },
            {
              value: 'GENETIC',
              label: 'Genetic data (special category)',
              riskTags: ['tag:special-category'],
            },
            {
              value: 'BIOMETRIC',
              label: 'Biometric data for identification (special category)',
              riskTags: ['tag:special-category', 'tag:biometric'],
            },
            {
              value: 'RACIAL_ETHNIC',
              label: 'Racial or ethnic origin (special category)',
              riskTags: ['tag:special-category'],
            },
            {
              value: 'POLITICAL_OPINIONS',
              label: 'Political opinions (special category)',
              riskTags: ['tag:special-category'],
            },
            {
              value: 'RELIGIOUS_BELIEFS',
              label: 'Religious or philosophical beliefs (special category)',
              riskTags: ['tag:special-category'],
            },
            {
              value: 'SEX_LIFE_ORIENTATION',
              label: 'Sex life / sexual orientation (special category)',
              riskTags: ['tag:special-category'],
            },
            {
              value: 'CRIMINAL_CONVICTIONS',
              label: 'Criminal convictions / offences (Art. 10)',
              riskTags: ['tag:criminal'],
            },
          ],
          references: ['UK GDPR Art. 9', 'UK GDPR Art. 10'],
        },
        {
          key: 'subjects_count',
          type: 'SINGLE_SELECT',
          label: 'Approximately how many data subjects are affected?',
          required: true,
          options: [
            { value: 'lt_1k', label: 'Fewer than 1,000' },
            { value: '1k_10k', label: '1,000 – 10,000' },
            { value: '10k_100k', label: '10,000 – 100,000' },
            { value: 'gte_100k', label: 'More than 100,000', riskTags: ['tag:large-scale'] },
          ],
          references: ['EDPB WP248 (large scale factors)'],
        },
        {
          key: 'children_subjects',
          type: 'BOOLEAN',
          label: 'Does the processing involve children (under 18)?',
          required: true,
          references: ["ICO Children's Code"],
        },
        {
          key: 'children_safeguards',
          type: 'TEXTAREA',
          label: 'What age-assurance and child-specific safeguards are in place?',
          required: true,
          visibleWhen: { q: 'children_subjects', op: 'eq', value: true },
          aiHint:
            "Address age verification, parental consent where required (Art. 8), and Children's Code standards (best interests, default settings).",
        },
        {
          key: 'data_sources',
          type: 'MULTI_SELECT',
          label: 'Where is the data obtained from?',
          required: true,
          options: [
            { value: 'direct', label: 'Directly from the data subject' },
            { value: 'third_party', label: 'Third parties / partners' },
            {
              value: 'public_sources',
              label: 'Publicly available sources',
              riskTags: ['tag:scraped-data'],
            },
            { value: 'scraping', label: 'Web scraping', riskTags: ['tag:scraped-data'] },
            { value: 'devices', label: 'Devices / sensors / telemetry', riskTags: ['tag:iot'] },
          ],
        },
        {
          key: 'retention_period',
          type: 'SINGLE_SELECT',
          label: 'How long is the data retained?',
          required: true,
          references: ['UK GDPR Art. 5(1)(e)'],
          options: [
            { value: 'under_1y', label: 'Under 1 year' },
            { value: '1_3y', label: '1 – 3 years' },
            { value: '3_7y', label: '3 – 7 years' },
            { value: 'over_7y', label: 'More than 7 years' },
            {
              value: 'indefinite',
              label: 'No defined limit',
              riskTags: ['tag:indefinite-retention'],
            },
          ],
        },
        {
          key: 'retention_justification',
          type: 'TEXTAREA',
          label: 'Justify the retention period (legal or business requirement).',
          required: true,
          visibleWhen: { q: 'retention_period', op: 'in', value: ['over_7y', 'indefinite'] },
        },
      ],
    },
    {
      key: 'technology',
      title: 'Technology and security',
      questions: [
        {
          key: 'technologies',
          type: 'MULTI_SELECT',
          label: 'Which technologies are involved?',
          required: true,
          options: [
            { value: 'cloud', label: 'Cloud hosting' },
            { value: 'mobile_app', label: 'Mobile application' },
            { value: 'iot', label: 'IoT / connected devices', riskTags: ['tag:iot'] },
            {
              value: 'cookies_tracking',
              label: 'Cookies / tracking technologies',
              riskTags: ['tag:tracking'],
            },
            {
              value: 'facial_recognition',
              label: 'Facial recognition',
              riskTags: ['tag:facial-recognition', 'tag:biometric'],
            },
            { value: 'cctv', label: 'CCTV / video surveillance' },
            { value: 'api_integrations', label: 'Third-party API integrations' },
          ],
        },
        {
          key: 'cloud_providers',
          type: 'MULTI_SELECT',
          label: 'Which cloud providers host the data?',
          required: true,
          visibleWhen: { q: 'technologies', op: 'includes', value: 'cloud' },
          options: [
            { value: 'aws', label: 'Amazon Web Services' },
            { value: 'azure', label: 'Microsoft Azure' },
            { value: 'gcp', label: 'Google Cloud' },
            { value: 'other', label: 'Other / private cloud' },
          ],
        },
        {
          key: 'uses_ai',
          type: 'BOOLEAN',
          label: 'Does the processing use AI or machine learning?',
          required: true,
          references: ['ICO AI and data protection guidance'],
        },
        {
          key: 'ai_purpose',
          type: 'TEXTAREA',
          label: 'What does the AI system do, and what data does it use?',
          required: true,
          visibleWhen: { q: 'uses_ai', op: 'eq', value: true },
          aiHint:
            'Describe the model type, inputs/outputs, whether personal data is used for training, and human oversight arrangements.',
        },
        {
          key: 'ai_training_data',
          type: 'TEXTAREA',
          label: 'Is personal data used to train or fine-tune models? How is it protected?',
          visibleWhen: { q: 'uses_ai', op: 'eq', value: true },
        },
        {
          key: 'automated_decisions',
          type: 'BOOLEAN',
          label:
            'Are decisions with legal or similarly significant effects made solely automatically?',
          required: true,
          references: ['UK GDPR Art. 22'],
        },
        {
          key: 'automated_decisions_detail',
          type: 'TEXTAREA',
          label: 'Describe the decision logic, significance, and the human review mechanism.',
          required: true,
          visibleWhen: { q: 'automated_decisions', op: 'eq', value: true },
        },
        {
          key: 'encryption_at_rest',
          type: 'BOOLEAN',
          label: 'Is personal data encrypted at rest?',
          required: true,
          references: ['UK GDPR Art. 32(1)(a)'],
        },
        {
          key: 'encryption_in_transit',
          type: 'BOOLEAN',
          label: 'Is personal data encrypted in transit (TLS)?',
          required: true,
          references: ['UK GDPR Art. 32(1)(a)'],
        },
        {
          key: 'access_controls',
          type: 'MULTI_SELECT',
          label: 'Which access controls protect the data?',
          required: true,
          options: [
            { value: 'rbac', label: 'Role-based access control' },
            { value: 'mfa', label: 'Multi-factor authentication' },
            { value: 'sso', label: 'Single sign-on' },
            { value: 'joiner_leaver', label: 'Joiner/mover/leaver process' },
            { value: 'none', label: 'No formal access control', riskTags: ['tag:weak-access'] },
          ],
        },
        {
          key: 'security_measures',
          type: 'TEXTAREA',
          label: 'Describe other technical and organisational security measures.',
          help: 'e.g. pseudonymisation, backups, monitoring, penetration testing, staff training.',
        },
      ],
    },
    {
      key: 'sharing',
      title: 'Sharing and international transfers',
      questions: [
        {
          key: 'third_party_processors',
          type: 'BOOLEAN',
          label: 'Are third-party processors used?',
          required: true,
          references: ['UK GDPR Art. 28'],
        },
        {
          key: 'processors_list',
          type: 'TEXTAREA',
          label: 'List the processors and what each one does.',
          required: true,
          visibleWhen: { q: 'third_party_processors', op: 'eq', value: true },
        },
        {
          key: 'dpa_in_place',
          type: 'BOOLEAN',
          label: 'Are Art. 28 data processing agreements in place with every processor?',
          required: true,
          visibleWhen: { q: 'third_party_processors', op: 'eq', value: true },
        },
        {
          key: 'international_transfers',
          type: 'BOOLEAN',
          label: 'Is personal data transferred outside the UK?',
          required: true,
          references: ['UK GDPR Art. 44–49'],
        },
        {
          key: 'transfer_countries',
          type: 'TEXT',
          label: 'Which countries receive the data?',
          required: true,
          visibleWhen: { q: 'international_transfers', op: 'eq', value: true },
        },
        {
          key: 'transfer_mechanism',
          type: 'SINGLE_SELECT',
          label: 'Which transfer mechanism is relied upon?',
          required: true,
          visibleWhen: { q: 'international_transfers', op: 'eq', value: true },
          options: [
            { value: 'ADEQUACY', label: 'UK adequacy regulations' },
            { value: 'IDTA', label: 'International Data Transfer Agreement (IDTA)' },
            { value: 'SCC_ADDENDUM', label: 'EU SCCs + UK Addendum' },
            { value: 'BCR', label: 'Binding Corporate Rules' },
            { value: 'DEROGATION', label: 'Art. 49 derogation' },
            { value: 'NONE', label: 'None yet', riskTags: ['tag:restricted-transfer'] },
          ],
          references: ['ICO international transfers guidance'],
        },
      ],
    },
    {
      key: 'rights',
      title: 'Rights, transparency and consultation',
      questions: [
        {
          key: 'privacy_notice',
          type: 'BOOLEAN',
          label: 'Are data subjects given privacy information covering this processing?',
          required: true,
          references: ['UK GDPR Art. 13', 'UK GDPR Art. 14'],
        },
        {
          key: 'dsar_process',
          type: 'BOOLEAN',
          label: 'Is there a process to handle data subject rights requests within one month?',
          required: true,
          references: ['UK GDPR Art. 12(3)'],
        },
        {
          key: 'public_monitoring',
          type: 'BOOLEAN',
          label: 'Does the processing systematically monitor publicly accessible areas?',
          required: true,
          references: ['UK GDPR Art. 35(3)(c)'],
        },
        {
          key: 'subjects_consulted',
          type: 'BOOLEAN',
          label: 'Have data subjects (or their representatives) been consulted?',
          required: true,
          references: ['UK GDPR Art. 35(9)'],
        },
        {
          key: 'consultation_detail',
          type: 'TEXTAREA',
          label: 'Summarise the consultation, or justify why it was not appropriate.',
          required: true,
          visibleWhen: { q: 'subjects_consulted', op: 'answered' },
        },
        {
          key: 'necessity_proportionality',
          type: 'TEXTAREA',
          label: 'Explain why the processing is necessary and proportionate to the purpose.',
          required: true,
          references: ['UK GDPR Art. 35(7)(b)'],
          aiHint:
            'Address: could the purpose be achieved with less data, less intrusive means, or shorter retention? Why not?',
        },
      ],
    },
  ],
};
