import { REPORT_TEMPLATES, type ReportModel, type ReportTemplateKey } from '../report-model';

export function renderMarkdown(model: ReportModel, template: ReportTemplateKey): string {
  const inc = REPORT_TEMPLATES[template];
  const lines: string[] = [
    `# Data Protection Impact Assessment — ${model.title}`,
    '',
    `| | |`,
    `|---|---|`,
    `| Reference | ${model.reference} |`,
    `| Organisation | ${model.organisation} |`,
    `| Status | ${model.status} |`,
    `| Completeness | ${model.completeness}% |`,
    `| Generated | ${model.generatedAt} |`,
    ...(model.approvedAt ? [`| Approved | ${model.approvedAt} |`] : []),
    ...(model.nextReviewAt ? [`| Next review | ${model.nextReviewAt} |`] : []),
    '',
  ];
  if (model.description) lines.push(model.description, '');

  lines.push(
    '## Article 36 prior consultation',
    '',
    model.priorConsultation.required
      ? '**REQUIRED** — consult the ICO before starting processing.'
      : '**Not indicated** on residual-risk grounds alone.',
    '',
    model.priorConsultation.reason,
    '',
  );

  if (inc.questionnaire) {
    for (const section of model.sections) {
      lines.push(`## ${section.title}`, '');
      for (const item of section.items) {
        lines.push(`**${item.question}**`, '', item.answer, '');
        if (item.references?.length) lines.push(`> ${item.references.join(' · ')}`, '');
      }
    }
  }

  if (inc.risks && model.risks.length > 0) {
    lines.push('## Identified risks', '');
    lines.push(
      '| Risk | Category | L | I | Inherent | Residual | Level | Status |',
      '|---|---|---|---|---|---|---|---|',
    );
    for (const r of model.risks) {
      lines.push(
        `| ${r.title} | ${r.category} | ${r.likelihood} | ${r.impact} | ${r.inherentScore} | ${r.residualScore} | ${r.residualLevel} | ${r.status} |`,
      );
    }
    lines.push('');
    for (const r of model.risks) {
      if (r.controls.length > 0) {
        lines.push(
          `- **${r.title}** — controls: ${r.controls.map((c) => `${c.name} (${c.status})`).join('; ')}`,
        );
      }
      if (r.references.length > 0) {
        lines.push(`  - References: ${r.references.join(' · ')}`);
      }
    }
    lines.push('');
  }

  if (model.dataFlowFindings.length > 0) {
    lines.push('## Data flow findings', '');
    for (const f of model.dataFlowFindings) lines.push(`- **[${f.severity}]** ${f.message}`);
    lines.push('');
  }

  if (inc.controls && model.controls.length > 0) {
    lines.push('## Controls', '', '| Control | Status | Framework mappings |', '|---|---|---|');
    for (const c of model.controls) {
      lines.push(`| ${c.name} | ${c.status} | ${c.frameworks.join(', ') || '—'} |`);
    }
    lines.push('');
  }

  if (inc.approvals && model.approvals.length > 0) {
    lines.push('## Approvals', '');
    for (const a of model.approvals) {
      lines.push(
        `- ${a.decidedAt} — **${a.decision}** at stage ${a.stage}${a.comment ? `: ${a.comment}` : ''}`,
      );
    }
    lines.push('');
  }

  if (inc.history && model.workflowHistory.length > 0) {
    lines.push('## Workflow history', '');
    for (const h of model.workflowHistory) {
      lines.push(`- ${h.at}: ${h.from} → ${h.to}${h.comment ? ` — ${h.comment}` : ''}`);
    }
    lines.push('');
  }

  lines.push('---', '*Generated by Shieldwise Privacy Platform.*');
  return lines.join('\n');
}

export function renderHtml(model: ReportModel, template: ReportTemplateKey): string {
  const md = renderMarkdown(model, template);
  // Deliberately minimal markdown→HTML conversion (headings, bold, tables, lists)
  // to avoid a runtime dependency; report fidelity formats are PDF/DOCX.
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const bodyParts: string[] = [];
  let tableBuffer: string[] = [];

  const flushTable = () => {
    if (tableBuffer.length === 0) return;
    const rows = tableBuffer.filter((r) => !/^\|[-\s|]+\|$/.test(r));
    const html = rows
      .map((row, i) => {
        const cells = row
          .split('|')
          .slice(1, -1)
          .map((c) => c.trim());
        const tag = i === 0 ? 'th' : 'td';
        return `<tr>${cells.map((c) => `<${tag}>${inline(c)}</${tag}>`).join('')}</tr>`;
      })
      .join('');
    bodyParts.push(`<table>${html}</table>`);
    tableBuffer = [];
  };
  const inline = (s: string) =>
    esc(s)
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.+?)\*/g, '<em>$1</em>');

  for (const line of md.split('\n')) {
    if (line.startsWith('|')) {
      tableBuffer.push(line);
      continue;
    }
    flushTable();
    if (line.startsWith('# ')) bodyParts.push(`<h1>${inline(line.slice(2))}</h1>`);
    else if (line.startsWith('## ')) bodyParts.push(`<h2>${inline(line.slice(3))}</h2>`);
    else if (line.startsWith('> '))
      bodyParts.push(`<blockquote>${inline(line.slice(2))}</blockquote>`);
    else if (line.startsWith('- ')) bodyParts.push(`<li>${inline(line.slice(2))}</li>`);
    else if (line === '---') bodyParts.push('<hr/>');
    else if (line.trim() === '') bodyParts.push('');
    else bodyParts.push(`<p>${inline(line)}</p>`);
  }
  flushTable();

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<title>${esc(model.reference)} — ${esc(model.title)}</title>
<style>
  body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:860px;margin:2rem auto;padding:0 1rem;color:#1a202c;line-height:1.55}
  table{border-collapse:collapse;width:100%;margin:1rem 0}
  th,td{border:1px solid #cbd5e0;padding:.4rem .6rem;text-align:left;font-size:.9rem}
  th{background:#edf2f7}
  blockquote{color:#4a5568;border-left:3px solid #cbd5e0;margin:0;padding-left:.75rem;font-size:.85rem}
  h1{border-bottom:2px solid #2b6cb0;padding-bottom:.3rem}
</style></head><body>${bodyParts.join('\n')}</body></html>`;
}

export function renderCsv(model: ReportModel): string {
  const esc = (v: unknown) => `"${String(v ?? '').replace(/"/g, '""')}"`;
  const rows = [
    [
      'reference',
      'risk',
      'category',
      'likelihood',
      'impact',
      'inherent_score',
      'residual_score',
      'level',
      'residual_level',
      'status',
      'controls',
    ].join(','),
    ...model.risks.map((r) =>
      [
        esc(model.reference),
        esc(r.title),
        esc(r.category),
        r.likelihood,
        r.impact,
        r.inherentScore,
        r.residualScore,
        esc(r.level),
        esc(r.residualLevel),
        esc(r.status),
        esc(r.controls.map((c) => `${c.name} (${c.status})`).join('; ')),
      ].join(','),
    ),
  ];
  return rows.join('\n');
}
